Homework-12 Ansible-03
Otus-DevOps-2017-11/etozhecyber_infra pull request #9
Opened 2018-01-21 15:56 UTC by etozhecyber

Установка приложения и базы данных разнесены по ролям. Также добавлены 2 окружения stage и prod

2018-01-24 10:10 UTC, Nklya requested changes
Будет проверено после мержа всех предыдущих дз. 
Такой дифф нечитабелен.

2018-01-25 17:53 UTC, etozhecyber commented
Замерджил предыдущии задания!

2018-01-25 20:31 UTC, Nklya requested changes
Добрый вечер.

Нужно:
1. Сделай мерж мастера в эту ветку и пофикси конфликты. 
2. В ридми нет инфы о том, что сделано.

2018-01-25 20:31 UTC, Nklya commented on terraform/modules/app/main.tf
> +resource "google_compute_instance" "app" {
С чего вдруг здесь тераформ появляется?

2018-01-25 21:01 UTC, Nklya commented
Плюс, скрипты из корня должны быть в директории config-scripts

2018-01-29 11:58 UTC, Nklya requested changes
Почти все ок.

Нужно:
1. Добавить в ридми что сделано
2. Файлы из корня нужно было перенести в config-scrips, а не закоммитить еще раз.

2018-01-29 11:58 UTC, Nklya commented on config-scripts/install_mongodb.sh
> +#!/bin/bash
Перенести значит переместить эти файлы из корня репозитория сюда, а не закоммитить еще одну копию.

2018-01-29 11:58 UTC, Nklya commented on config-scripts/install_ruby.sh
> +#!/bin/bash
Перенести значит переместить эти файлы из корня репозитория сюда, а не закоммитить еще одну копию.

2018-01-29 11:58 UTC, Nklya commented on config-scripts/startup.sh
> +#!/bin/bash
Перенести значит переместить эти файлы из корня репозитория сюда, а не закоммитить еще одну копию.

2018-01-29 11:58 UTC, Nklya commented on config-scripts/deploy.sh
> +#!/bin/bash
Перенести значит переместить эти файлы из корня репозитория сюда, а не закоммитить еще одну копию.

2018-02-03 18:47 UTC, etozhecyber commented on config-scripts/deploy.sh
> +#!/bin/bash
Забыл добавить удаленные файлы через git add . только новые добавил :(

2018-02-03 18:47 UTC, etozhecyber commented
Ну сейчас то точно все :)

2018-02-03 18:57 UTC, Nklya approved these changes
Да, теперь ок.

2018-02-03 20:27 UTC, merged